//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nettbutikk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Product
    {
        [Key]
        public Guid Id { get; set; }

        public string Name { get; set; }
        public float Price { get; set; }
        public string Description { get; set; }

        [ForeignKey("CategoryId")]
        public Guid CategoryId { get; set; }

        public virtual Category Category { get; set; }
    }
}
